#General settings
#host: 127.0.0.1
host: 0.0.0.0
port: 4222

# Jetstream NATS config for data persistence
# store_dir need to be created on disk ! With nats:nats owner:group !
jetstream {
    store_dir: /data/jetstream
    max_mem: 100M
    max_file: 10M
    #domain: acme
	
    # Sync time : 1m, 30s, always
    # Only for version >= 2.10.0
    # sync_interval: always
}

websocket {
    #port: 4223
    #no_tls: true
    port: 4443
    tls {
      cert_file: "/device/ascolab/cert/localhost.crt"
      key_file: "/device/ascolab/cert/localhost.key"
    }
}
